language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get install libv8-dev g++
  - pecl install v8js-0.1.3
  - phpenv config-add travis_php.ini 

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit